### model
model_name_or_path: Qwen/Qwen3-1.7B-Base
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json
flash_attn: auto
enable_liger_kernel: false

### dataset
dataset: OpenThought3-4B
template: qwen3
enable_thinking: false
cutoff_len: 4096
preprocessing_num_workers: 32
dataloader_num_workers: 16

### output
output_dir: ../model/Qwen3-1.7B-Base-SFT-smoke
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 1.0e-5
max_steps: 100
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.02
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 50
